export const SAVE_ADDRESS = "SAVE_ADDRESS";
export const GET_USERINFO = "GET_USERINFO";
export const RECORD_USERINFO = "RECORD_USERINFO";
export const SAVE_SEARCHHISTORY = "SAVE_SEARCHHISTORY";
export const GET_SEARCHHISTORY = "GET_SEARCHHISTORY";
export const DELETE_SEARCHHISTORY = "DELETE_SEARCHHISTORY";
export const CLEAR_SEARCHHISTORY = "CLEAR_SEARCHHISTORY";
